[functions.create-weekly-tournaments]
verify_jwt = false

[functions.create_daily_tournaments]
enabled = true
verify_jwt = true
import_map = "./functions/create_daily_tournaments/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_daily_tournaments/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_daily_tournaments/*.html" ]

[functions.resolve_day]
enabled = true
verify_jwt = true
import_map = "./functions/resolve_day/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resolve_day/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resolve_day/*.html" ]

[functions.join_tournament]
enabled = true
verify_jwt = true
import_map = "./functions/join_tournament/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/join_tournament/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/join_tournament/*.html" ]

[functions.list_tournaments]
enabled = true
verify_jwt = true
import_map = "./functions/list_tournaments/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/list_tournaments/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/list_tournaments/*.html" ]

[functions.game_slate]
enabled = true
verify_jwt = true
import_map = "./functions/game_slate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/game_slate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/game_slate/*.html" ]

[functions.sports_meta]
enabled = true
verify_jwt = true
import_map = "./functions/sports_meta/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sports_meta/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sports_meta/*.html" ]

[functions.submit_pick]
enabled = true
verify_jwt = true
import_map = "./functions/submit_pick/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit_pick/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit_pick/*.html" ]

[functions.create_nfl_tournament]
enabled = true
verify_jwt = true
import_map = "./functions/create_nfl_tournament/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_nfl_tournament/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_nfl_tournament/*.html" ]

[functions.create-wallet-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/create-wallet-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-wallet-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-wallet-checkout/*.html" ]

[functions.square-payment-updated]
enabled = true
verify_jwt = true
import_map = "./functions/square-payment-updated/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/square-payment-updated/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/square-payment-updated/*.html" ]

[functions.square-redirect]
enabled = true
verify_jwt = true
import_map = "./functions/square-redirect/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/square-redirect/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/square-redirect/*.html" ]

[functions.get-betting-markets]
enabled = true
verify_jwt = true
import_map = "./functions/get-betting-markets/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-betting-markets/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-betting-markets/*.html" ]

[functions.sync_results]
enabled = true
verify_jwt = true
import_map = "./functions/sync_results/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync_results/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync_results/*.html" ]

[functions.resolve_tournament_results]
enabled = true
verify_jwt = true
import_map = "./functions/resolve_tournament_results/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resolve_tournament_results/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resolve_tournament_results/*.html" ]
